---
name: Checks

"on":
  pull_request:
    branches:
      - main

jobs:
  Checks:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v4
        with:
          cache: true
          go-version-file: go.mod

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - name: Download go dependencies
        run: go mod download

      - name: Test
        run: make test
