---
name: Release

"on":
  push:
    branches:
      - main

jobs:
  release:
    name: Release to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: go.mod

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version-file: 'package.json'

      - name: Download go dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Release
        run: |
          npm version --no-git-tag-version $(go list -m -f '{{.Version}}' github.com/open-policy-agent/opa)-$(git rev-parse --short HEAD)
          npm publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
